export default [
  {
    name: 'Parkway 3mi',
    distance: 3.2,
    sport: 'Running',
    hills: 'Easy',
  },
  {
    name: 'Parkway 5mi',
    distance: 5.1,
    sport: 'Running',
    hills: 'Easy',
  },
  {
    name: 'Neighborhood 3mi',
    distance: 3.3,
    sport: 'Running',
    hills: 'Medium',
  },
  {
    name: 'Neighborhood 5mi',
    distance: 5.4,
    sport: 'Running',
    hills: 'Medium',
  },
  {
    name: 'Neighborhood 7mi',
    distance: 7.0,
    sport: 'Running',
    hills: 'Medium',
  },
  {
    name: 'Hoyt Trail Run',
    distance: 3.5,
    sport: 'Trail Running',
    hills: 'Easy',
  },
  {
    name: 'Hoyt MTB',
    distance: 2.2,
    sport: 'Mountain Biking',
    hills: 'Easy',
  },
  {
    name: 'Lapham Peak',
    distance: 3.3,
    sport: 'Trail Running',
    hills: 'Hard',
  },
  {
    name: 'Alpine Valley',
    distance: 7.7,
    sport: 'Mountain Biking',
    hills: 'Hard',
  },
  {
    name: 'Oak Leaf',
    distance: 17.0,
    sport: 'Cycling',
    hills: 'Easy',
  },
  {
    name: 'Minooka',
    distance: 4.0,
    sport: 'Mountain Biking',
    hills: 'Medium',
  },
  {
    name: 'Home to Oak Hill',
    distance: 10.2,
    sport: 'Mountain Biking',
    hills: 'Medium',
  },
  {
    name: 'Scuppernong 5k',
    distance: 3.3,
    sport: 'Trail Running',
    hills: 'Hard',
  },
  {
    name: 'Scuppernong 10k',
    distance: 6.4,
    sport: 'Trail Running',
    hills: 'Hard',
  },
  {
    name: 'Home to New Berlin Trail',
    distance: 20.1,
    sport: 'Cycling',
    hills: 'Easy',
  },
  {
    name: 'New Berlin Trail',
    distance: 18.0,
    sport: 'Cycling',
    hills: 'Easy',
  },
  {
    name: 'Devils Lake',
    distance: 25.3,
    sport: 'Cycling',
    hills: 'Hard',
  },
  {
    name: 'New Glarus',
    distance: 22.8,
    sport: 'Cycling',
    hills: 'Hard',
  },
];
